services:
  db:
    image: postgres:15
    platform: linux/amd64
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/local_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"